name: .NET Standard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: | 
          2.2.x
          6.0.x 
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
    
    - name: Autobuild
      id: build
      uses: github/codeql-action/autobuild@v2
    
    - name: Perform CodeQL Analysis
      id: CodeQL_analysis
      uses: github/codeql-action/analyze@v2
    
    - name: Test
      id: test
      run: dotnet test tests/Autodesk.Forge.Core.Test/Autodesk.Forge.Core.Test.csproj
    
    - name: Publish
      id: publish_to_Nuget
      if: ${{ github.event_name =='push' && github.ref == 'refs/heads/main'}}
      run: |
       dotnet msbuild src/Autodesk.Forge.Core/Autodesk.Forge.Core.csproj /t:Push
       dotnet msbuild src/Autodesk.Forge.Core.E2eTestHelpers/Autodesk.Forge.Core.E2eTestHelpers.csproj /t:Push
      env:
        NugetApiKey: ${{ secrets.NUGETAPIKEYBYENGOPS }}
